### PR TITLE
build(rocr): Fix debug builds with clang

### PR DESCRIPTION
**Pull request by lancesix**
## Motivation

When creating debuild build with clang, we have build failures introduced by 99a0be1e16 "rocr/coredump: Extend list of required memory ranges for lightweight cores":

    .../libamdhsacode/lnx/amd_core_dump.cpp:315:46: warning: flag '#' results in undefined
          behavior with 'p' conversion specifier [-Wformat]
      315 |       debug_print("Added aql_queue_t range: %#p - %#p (size: %zu)\n",
          |                                             ~^~
    .../core/util/utils.h:161:21: note: expanded from macro 'debug_print'
      161 |     fprintf(stderr, fmt, ##__VA_ARGS__);                                                           \
          |                     ^~~
    .../libamdhsacode/lnx/amd_core_dump.cpp:315:52: warning: flag '#' results in undefined
          behavior with 'p' conversion specifier [-Wformat]
      315 |       debug_print("Added aql_queue_t range: %#p - %#p (size: %zu)\n",
          |                                                   ~^~
    .../core/util/utils.h:161:21: note: expanded from macro 'debug_print'
      161 |     fprintf(stderr, fmt, ##__VA_ARGS__);                                                           \
          |                     ^~~
    .../libamdhsacode/lnx/amd_core_dump.cpp:325:21: error: arithmetic on a pointer to void
      324 |                   static_cast<void*>(aql_queue->amd_queue_.hsa_queue.base_address)
          |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      325 |                     + aql_queue->amd_queue_.hsa_queue.size * sizeof(hsa_kernel_dispatch_packet_t),
          |                     ^
    .../core/util/utils.h:161:28: note: expanded from macro 'debug_print'
      161 |     fprintf(stderr, fmt, ##__VA_ARGS__);                                                           \
          |                            ^~~~~~~~~~~
    .../libamdhsacode/lnx/amd_core_dump.cpp:339:65: error: arithmetic on a pointer to void
      339 |                   static_cast<void*>(queue_info.SaveAreaHeader) + queue_info.SaveAreaSizeInBytes,
          |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    .../core/util/utils.h:161:28: note: expanded from macro 'debug_print'
      161 |     fprintf(stderr, fmt, ##__VA_ARGS__);                                                           \
          |                            ^~~~~~~~~~~
    2 warnings and 2 errors generated.

This issue does not affect release build, and is not raised by GCC on debug builds either.

This patch fixes those build issues.

## Technical Details

Do not use `+` on `void *` pointers.  Instead, convert the `void *` into a `uint64_t`, and then do math on this.  Also adjust the printf format to support uint64_t.

## Test Plan

Produce a debug build.

## Test Result

PASS.

## Submission Checklist

- [X] Look over the contributing guidelines at https://github.com/ROCm/rocm-systems/blob/develop/CONTRIBUTING.md.

### CODE REVIEW

**Review by lamb-j — APPROVED** [review]
Fixes the issues hit with the Compiler SPIRV CI, thanks!

**Review by cfreeamd — COMMENTED** [review]
🤖 AI-assisted pre-review (for @cfreeamd)

`amd_core_dump.cpp` looks correct. All three `debug_print` conversions replace the non-standard `%#p` flag and the illegal `void*` arithmetic (`static_cast<void*>(...) + N`) with `reinterpret_cast<uint64_t>(...)` + `PRIx64`; the end-address arithmetic in each case matches the adjacent `filter.add_range()` call. (Minor: worth a glance that `<cinttypes>` is included for `PRIx64`, though CI passing implies it is.)

**Comment by lancesix** [comment]
> 🤖 AI-assisted pre-review (for @cfreeamd)
> 
> `amd_core_dump.cpp` looks correct. All three `debug_print` conversions replace the non-standard `%#p` flag and the illegal `void*` arithmetic (`static_cast<void*>(...) + N`) with `reinterpret_cast<uint64_t>(...)` + `PRIx64`; the end-address arithmetic in each case matches the adjacent `filter.add_range()` call. (Minor: worth a glance that `<cinttypes>` is included for `PRIx64`, though CI passing implies it is.)

`cinttypes` is not included directly, it is transitively imported from `core/inc/runtime.h`.  Could change it if requested.

Note that uint64_t was already widely used in this file, this patch does not add any new include requirement, just leverage what is already there.

**Review by dayatsin-amd — APPROVED** [review]
