### PR TITLE
AIRUNTIME-1933 - refactor(hip-tests): remove redundant title strings from hip_tests_co…

### PR DESCRIPTION
**Pull request by JDas-AMD**
## Summary

Remove redundant title strings from the generated hip_test_config.hh macros to simplify the macro system and reduce preprocessor complexity.

## Motivation

The current implementation of parse_config.py generates macros with a redundant title string as the first element that is never used. This requires complex preprocessor indirection (SECOND_ARG and GET_TAGS macros) to extract just the tags, adding unnecessary complexity to the build system.

## Technical Details

**Problem:**
The generated hip_test_config.hh macros included a redundant title string:
```cpp
#define Unit_Test_Name "Unit_Test_Name", "[tag1][tag2]"
```

This required complex preprocessor indirection with 4 macros where only 2 are needed.

Solution:
Modified the macro generation to produce a simplified format:

```cpp
#define Unit_Test_Name "[tag1][tag2]"
```
Files Modified:

projects/hip-tests/catch/config/parse_config.py (line 77):

Changed: return f'#define {case_name} "{case_name}", "{tags_str}"'
To: return f'#define {case_name} "{tags_str}"'
projects/hip-tests/catch/include/hip_test_common.hh (lines 26-32):

Removed SECOND_ARG and GET_TAGS macros
Simplified HIP_TEST_CASE and HIP_TEMPLATE_TEST_CASE to use direct substitution

## Test Result
Generated Config Header:
Macros now use simplified format:

```
#define Unit_StaticAssert_Positive_Basic_RTC "[deviceLib][level_2][assertion][gfx1201]"
```
Instead of:

```
#define Unit_StaticAssert_Positive_Basic_RTC "Unit_StaticAssert_Positive_Basic_RTC", "[deviceLib][level_2][assertion]
[gfx1201]"
```
Build:
hip-tests builds successfully with no compilation errors or warnings

Macro Expansion:
Test macros expand correctly:

// HIP_TEST_CASE(Unit_StaticAssert_Positive_Basic_RTC) expands to:
TEST_CASE("Unit_StaticAssert_Positive_Basic_RTC", "[deviceLib][level_2][assertion][gfx1201]")

### CODE REVIEW

**Review by AlexXAmd — APPROVED** [review]

**Review by AlexXAmd — CHANGES_REQUESTED** [review]
Test first

**Comment by JDas-AMD** [comment]
Closed: a bad merge pulled in unrelated public develop commits and mis-fired CODEOWNERS. Nothing to review here
