### PR TITLE
fix(rocprofiler-systems): skip rocshmem example for rocSHMEM < 3.6.0

### PR DESCRIPTION
**Pull request by sputhala-amd**
## Motivation

Building rocprofiler-systems against an older rocSHMEM (e.g. 3.2.0, shipped with ROCm 7.2.x) breaks the whole build because the `rocshmem` example calls host-stream APIs that only exist in rocSHMEM >= 3.6.0.

## Technical Details

`examples/rocshmem/rocshmem.cpp` exercises nine rocSHMEM host-stream APIs (`rocshmem_putmem_on_stream`, `rocshmem_getmem_on_stream`, etc.). rocSHMEM < 3.6.0 only declares `rocshmem_barrier_all_on_stream`, so the example failed to compile with "use of undeclared identifier" errors on machines where an older rocSHMEM is installed. 

CI never hit this because rocSHMEM is absent from the CI images and the and the example was already skipped via the existing `roc::rocshmem` not-found guard.

This adds a version guard in `examples/rocshmem/CMakeLists.txt`: when `rocshmem_VERSION < 3.6.0`, the `rocshmem-test` target is skipped with an explanatory message instead of failing the build. Builds with rocSHMEM >= 3.6.0 are unaffected.

## Issue Tracking

JIRA ID: AIPROFSYST-700

## Test Plan

Configured against ROCm 7.2.4 (rocSHMEM 3.2.0): CMake now emits `rocshmem-test skipped: rocSHMEM 3.2.0 lacks the host-stream APIs ...` and the build completes (previously failed to compile).

## Test Result

Pass on manual testing.

## Submission Checklist

- [X] Look over the contributing guidelines at https://github.com/ROCm/rocm-systems/blob/develop/CONTRIBUTING.md.

### CODE REVIEW

**Comment by ajanicijamd** [comment]
LGTM; but please fix the description: there is an unfinished sentence:
    `CI never hit this because rocSHMEM is absent from the CI images and the`

**Review by dgaliffiAMD — APPROVED** [review]
Approving CML change to this build issue. 

Do you think we also need a version check in the test definition, like we do for the rocprofiler-sdk version - (ex.,
https://github.com/ROCm/rocm-systems/blob/df246008f709b162dc330e269bbf08c829f8035a/projects/rocprofiler-systems/tests/pytest/test_rocshmem_tracing.py#L21).
If so, we can stack that change onto https://github.com/ROCm/rocm-systems/pull/9402

**Comment by sputhala-amd** [comment]
> Approving CML change to this build issue.
> 
> Do you think we also need a version check in the test definition, like we do for the rocprofiler-sdk version - (ex.,
> 
> https://github.com/ROCm/rocm-systems/blob/df246008f709b162dc330e269bbf08c829f8035a/projects/rocprofiler-systems/tests/pytest/test_rocshmem_tracing.py#L21
> 
> ).
> If so, we can stack that change onto #9402

No problem to add more defensive check for runtime with `rocshmem` version, but I think unless a user is actually messing around with their builds, probably SDK min version 1.3.4 should be enough. https://github.com/ROCm/rocm-systems/blob/develop/projects/rocshmem/CHANGELOG.md.
https://github.com/ROCm/rocm-systems/blob/45cc53a3fa516abde83cf033604d66232c8d782d/projects/rocshmem/CMakeLists.txt#L102.
So I would say not needed to do a `rocshmem` version check but no harm.
