### ISSUE TITLE
[rocr-runtime][rocdxg][WSL] error when linking librocdxg.so: `undefined reference to rocr::log_printf(char const*, int, char const*, ...)'`

### ISSUE THREAD

**Issue by dysu-amd** [ROCm/rocm-systems#8340]
### Description
All recent ROCR Runtime WSL CI checks are failing to link rocdxg:
https://github.com/ROCm/rocm-systems/actions/workflows/rocr-runtime-wsl.yml

examples:
https://github.com/ROCm/rocm-systems/actions/runs/29034141422/job/86174452532#step:10:405
https://github.com/ROCm/TheRock/actions/runs/29027555678/job/86156984352?pr=6447#step:20:576

### Error message
```
[30/31] Linking CXX shared library librocdxg.so.1.1.0
FAILED: librocdxg.so.1.1.0 
: && /usr/bin/c++ -fPIC   -Wl,--enable-new-dtags -Wl,--version-script=/root/rocm-systems/projects/rocr-runtime/libhsakmt/src/dxg/librocdxg.ver -Wl,-soname=librocdxg.so.1 -Wl,-z,nodelete -Wl,-no-undefined -shared -Wl,-soname,librocdxg.so.1 -o librocdxg.so.1.1.0 CMakeFiles/rocdxg.dir/src/dxg/debug.cpp.o CMakeFiles/rocdxg.dir/src/dxg/events.cpp.o CMakeFiles/rocdxg.dir/src/dxg/memory.cpp.o CMakeFiles/rocdxg.dir/src/dxg/libdrm.cpp.o CMakeFiles/rocdxg.dir/src/dxg/hsa.cpp.o CMakeFiles/rocdxg.dir/src/dxg/openclose.cpp.o CMakeFiles/rocdxg.dir/src/dxg/perfctr.cpp.o CMakeFiles/rocdxg.dir/src/dxg/queues.cpp.o CMakeFiles/rocdxg.dir/src/dxg/rocrstub.cpp.o CMakeFiles/rocdxg.dir/src/dxg/time.cpp.o CMakeFiles/rocdxg.dir/src/dxg/topology.cpp.o CMakeFiles/rocdxg.dir/src/dxg/topology_lnx.cpp.o CMakeFiles/rocdxg.dir/src/dxg/spm.cpp.o CMakeFiles/rocdxg.dir/src/dxg/version.cpp.o CMakeFiles/rocdxg.dir/src/dxg/svm.cpp.o CMakeFiles/rocdxg.dir/src/dxg/pc_sampling.cpp.o CMakeFiles/rocdxg.dir/src/dxg/hsakmtmodel.cpp.o CMakeFiles/rocdxg.dir/src/dxg/dxcore_loader.cpp.o CMakeFiles/rocdxg.dir/src/dxg/ais.cpp.o CMakeFiles/rocdxg.dir/src/dxg/wddm/device.cpp.o CMakeFiles/rocdxg.dir/src/dxg/wddm/event.cpp.o CMakeFiles/rocdxg.dir/src/dxg/wddm/gpu_memory.cpp.o CMakeFiles/rocdxg.dir/src/dxg/wddm/va_mgr.cpp.o CMakeFiles/rocdxg.dir/src/dxg/wddm/queue.cpp.o CMakeFiles/rocdxg.dir/src/dxg/wddm/cmd_util.cpp.o CMakeFiles/rocdxg.dir/src/dxg/extsem.cpp.o CMakeFiles/rocdxg.dir/root/rocm-systems/projects/rocr-runtime/runtime/hsa-runtime/core/util/timer.cpp.o CMakeFiles/rocdxg.dir/root/rocm-systems/projects/rocr-runtime/runtime/hsa-runtime/core/util/small_heap.cpp.o CMakeFiles/rocdxg.dir/root/rocm-systems/projects/rocr-runtime/runtime/hsa-runtime/core/util/lnx/os_linux.cpp.o -L/root/rocm-systems/projects/rocr-runtime/libhsakmt/../../../shared/amdgpu-windows-interop/wkmi/lnx/lib -Wl,-rpath,/root/rocm-systems/projects/rocr-runtime/libhsakmt/../../../shared/amdgpu-windows-interop/wkmi/lnx/lib:  -lwkmi  -lpthread  -lrt  -lc  -ldl && :
/usr/bin/ld: CMakeFiles/rocdxg.dir/root/rocm-systems/projects/rocr-runtime/runtime/hsa-runtime/core/util/lnx/os_linux.cpp.o: in function `rocr::os::DmaBufClose(int*)':
/root/rocm-systems/projects/rocr-runtime/runtime/hsa-runtime/core/util/lnx/os_linux.cpp:887:(.text+0x1e1a): undefined reference to `rocr::log_flags'
/usr/bin/ld: /root/rocm-systems/projects/rocr-runtime/runtime/hsa-runtime/core/util/lnx/os_linux.cpp:887:(.text+0x1e8d): undefined reference to `rocr::log_printf(char const*, int, char const*, ...)'
collect2: error: ld returned 1 exit status
```

### Cause
The error seems to have been introduced in https://github.com/ROCm/rocm-systems/pull/7803. The PR failed the WSL check but it's currently not a hard requirement for merging to develop.
