### PR TITLE
fix(rccl-tests): correct NCCL_CTA_POLICY_ZERO version guard to 2.28.0

### PR DESCRIPTION
**Pull request by JhaShweta1**
The getSymkInfo block in common.cu references NCCL_CTA_POLICY_ZERO, which is only defined in RCCL/NCCL 2.28+. The guard introduced in #8104 used NCCL_VERSION(2,27,0), so when building against RCCL 2.27.x (shipped in ROCm 7.1/7.2) the block is compiled but the symbol is undefined:

    error: use of undeclared identifier 'NCCL_CTA_POLICY_ZERO'

## Motivation

To build cleanly against RCCL 2.27.7.

## Technical Details

Bump both the compile-time guard and the matching runtime check to 2.28.0. On 2.27.x the block is compiled out and execution falls through to the existing !fromSymk path, which is the correct behavior for a pre-2.28 library. 

## Issue Tracking

JIRA ID: ROCM-28278

## Test Plan

Environment

GPU: AMD Instinct MI300X (gfx942)
ROCm 7.2.0, RCCL 2.27.7 (/opt/rocm, NCCL_MAJOR.MINOR.PATCH = 2.27.7)
Compiler: /opt/rocm/llvm/bin/amdclang++
Base: develop; change is projects/rccl-tests/src/common.cu guard NCCL_VERSION(2,27,0) → NCCL_VERSION(2,28,0)
Steps

- Build rccl-tests against a pre-2.28 RCCL (2.27.7) before the fix — expect the compile error.
- Build rccl-tests against the same RCCL 2.27.7 after the fix — expect a clean build.
- Confirm no behavior change for RCCL ≥ 2.28 (the guard still evaluates true, so the getSymkInfo path is unchanged).
`cd projects/rccl-tests
make MPI=0 NCCL_HOME=/opt/rocm HIP_HOME=/opt/rocm -j$(nproc)`

## Test Result

Before fix — RCCL 2.27.7 (fails):

common.cu:1115: error: use of undeclared identifier 'NCCL_CTA_POLICY_ZERO'
make[1]: *** [Makefile:195: .../common.o] Error 1
(The #if NCCL_VERSION_CODE >= NCCL_VERSION(2,27,0) block compiles under 2.27.x, but the symbol is only defined in RCCL 2.28+.)

After fix — RCCL 2.27.7 (builds cleanly):

RCCL ≥ 2.28 unaffected: with the guard at 2.28.0, NCCL_VERSION_CODE (≥ 22800) >= 22800 remains true, so the getSymkInfo block still compiles and behaves identically for 2.28+ builds. Verified separately that rccl-tests builds against RCCL 2.30.4.

Runtime sanity (default path, 2 GPUs):
all_reduce_perf -b 8 -e 8 -f 2 -g 2 -c 1 -n 1

## Submission Checklist

- [ ] Look over the contributing guidelines at https://github.com/ROCm/rocm-systems/blob/develop/CONTRIBUTING.md.

### CODE REVIEW

**Review by mch — APPROVED** [review]

**Comment by rahulvaidya20** [comment]
@JhaShweta1 This fix is already included here in the new nccl-tests sync branch: https://github.com/ROCm/rocm-systems/blob/users/rahulvaidya20/aicomrccl-1557-rccl-tests-sync/projects/rccl-tests/src/common.cu#L1319

**Comment by JhaShweta1** [comment]
> @JhaShweta1 This fix is already included here in the new nccl-tests sync branch: https://github.com/ROCm/rocm-systems/blob/users/rahulvaidya20/aicomrccl-1557-rccl-tests-sync/projects/rccl-tests/src/common.cu#L1319

@rahulvaidya20 Perfect! I will close this one.
